#
# Site Metadata
#
# - name: Site name
# _ baseurl: Optional URL to use where documentation is hosted in a subdirectory `domain.com/{baseurl}`
# - footer: Footer copy
# - logo: Menu bar logo
#
name: ADSS 
baseurl:
footer: SPAN Digital
logo: media/images/logo.png

#
# Menu Structure
#
# - tile: Menu item title
# - path: Path to generated article collection
# - collection: The collection to use for generating a sub menu of articles (optional).
#
structure:
  - title: "Overview"
    path: "/"

  - title: "Key Concepts"
    path: "/key-concepts/"
    collection: key_concepts

  - title: "Prerequisites"
    path: "/prerequisites/"
    collection: prerequisites

  - title: "Getting Started"
    path: "/getting-started/"
    collection: getting_started

  - title: "Reference"
    path: "/reference/"
    collection: reference

  - title: "Scenarios"
    path: "/scenarios/"
    collection: scenarios

  - title: "Best Practices"
    path: "/best-practices/"
    collection: best_practices   

  - title: "Recipes"
    path: "/recipes/"
    collection: recipes

  - title: "Glossay"
    path: "/glossary/"
    collection: glossary

  - title: "Tools"
    path: "/tools/"
    collection: tools

  - title: "Testing & Debugging"
    path: "/testing/"
    colletion: testing

  - title: "Updates"
    path: "/updates/"
    collection: updates

#
# Jekyll collections definitions that use layout templates from presidium-core
#
collections:
    best_practices:
    getting_started:
    key_concepts:
    overview:
    prerequisites:
    recipes:
    reference:
        output: true
        permalink: /reference/:path/
    glossary:
    testing:
    tools:
    scenarios:
    updates:

#
# Exclude the following files from the generated site
#
exclude: [
    "README.md",
    "LICENSE",
    "_TEMPLATE.md",
    ".gitignore"
]

#
# System wide defaults
#
defaults:
    -
        scope:
            path: ""
        values:
            layout: "container"

#
# Sass settings
#
sass:
    sass_dir: media/css/_sass
