#
# Site Metadata
#
# - name: Site name
# _ baseurl: Optional URL to use where documentation is hosted in a subdirectory `domain.com/{baseurl}`
# - footer: Footer copy
# - logo: Menu bar logo
# - show: Hide or show article components. Defaults to true
#
name: Presidium
baseurl:
footer: SPAN Digital
logo: media/images/logo.png
show:
  status: true
  author: true
external:
  authors-url: https://github.com/orgs/SPANDigital/people/

#
# Menu Structure
#
# - tile: Menu item title
# - path: Path to generated article collection
# - collection: The collection to use for generating a sub menu of articles (optional).
#
structure:
  - title: "Overview"
    path: "/"

  - title: "Prerequisites"
    path: "/prerequisites/"

  - title: "Key Concepts"
    path: "/key-concepts/"
    collection: key-concepts

  - title: "Getting Started"
    path: "/getting-started/"
    collection: getting-started

  - title: "Reference"
    path: "/reference/"
    collection: reference

  - title: "Recipes"
    path: "/recipes/"
    collection: recipes

  - title: "Tools"
    path: "/tools/"
    collection: tools

  - title: "Testing & Debugging"
    path: "/testing/"
    colletion: testing

  - title: "Updates"
    path: "/updates/"
    collection: updates

#
# Optional filters that may be used to filter articles by role.
#
roles:
  label: "Show documentation for role"
  all: "All Roles"
  options:
    - "Business Analyst"
    - "Developer"
    - "Tester"

#
# Jekyll collections definitions that use layout templates from presidium-core
#
collections:
    best-practices:
    getting-started:
    key-concepts:
    overview:
    prerequisites:
    recipes:
    reference:
        output: true
        permalink: /reference/:path/
    testing:
    tools:
    typical-scenarios:
    updates:

#
# Exclude the following files from the generated site
#
exclude: [
    "README.md",
    "LICENSE",
    "_TEMPLATE.md",
    ".gitignore"
]

#
# System wide defaults
#
defaults:
    -
        scope:
            path: ""
        values:
            layout: "container"

#
# Sass settings
#
sass:
    sass_dir: media/css/_sass